// Generated by gencpp from file sever_client/ADDintsResponse.msg
// DO NOT EDIT!


#ifndef SEVER_CLIENT_MESSAGE_ADDINTSRESPONSE_H
#define SEVER_CLIENT_MESSAGE_ADDINTSRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace sever_client
{
template <class ContainerAllocator>
struct ADDintsResponse_
{
  typedef ADDintsResponse_<ContainerAllocator> Type;

  ADDintsResponse_()
    : sum(0)  {
    }
  ADDintsResponse_(const ContainerAllocator& _alloc)
    : sum(0)  {
  (void)_alloc;
    }



   typedef int32_t _sum_type;
  _sum_type sum;





  typedef boost::shared_ptr< ::sever_client::ADDintsResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::sever_client::ADDintsResponse_<ContainerAllocator> const> ConstPtr;

}; // struct ADDintsResponse_

typedef ::sever_client::ADDintsResponse_<std::allocator<void> > ADDintsResponse;

typedef boost::shared_ptr< ::sever_client::ADDintsResponse > ADDintsResponsePtr;
typedef boost::shared_ptr< ::sever_client::ADDintsResponse const> ADDintsResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::sever_client::ADDintsResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::sever_client::ADDintsResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::sever_client::ADDintsResponse_<ContainerAllocator1> & lhs, const ::sever_client::ADDintsResponse_<ContainerAllocator2> & rhs)
{
  return lhs.sum == rhs.sum;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::sever_client::ADDintsResponse_<ContainerAllocator1> & lhs, const ::sever_client::ADDintsResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace sever_client

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::sever_client::ADDintsResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sever_client::ADDintsResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sever_client::ADDintsResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sever_client::ADDintsResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sever_client::ADDintsResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sever_client::ADDintsResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::sever_client::ADDintsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0ba699c25c9418c0366f3595c0c8e8ec";
  }

  static const char* value(const ::sever_client::ADDintsResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0ba699c25c9418c0ULL;
  static const uint64_t static_value2 = 0x366f3595c0c8e8ecULL;
};

template<class ContainerAllocator>
struct DataType< ::sever_client::ADDintsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sever_client/ADDintsResponse";
  }

  static const char* value(const ::sever_client::ADDintsResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::sever_client::ADDintsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 sum\n"
;
  }

  static const char* value(const ::sever_client::ADDintsResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::sever_client::ADDintsResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.sum);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ADDintsResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::sever_client::ADDintsResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::sever_client::ADDintsResponse_<ContainerAllocator>& v)
  {
    s << indent << "sum: ";
    Printer<int32_t>::stream(s, indent + "  ", v.sum);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SEVER_CLIENT_MESSAGE_ADDINTSRESPONSE_H
