set(_CATKIN_CURRENT_PACKAGE "tf_static")
set(tf_static_VERSION "0.0.0")
set(tf_static_MAINTAINER "xiang <xiang@todo.todo>")
set(tf_static_PACKAGE_FORMAT "2")
set(tf_static_BUILD_DEPENDS "roscpp" "rospy" "std_msgs")
set(tf_static_BUILD_EXPORT_DEPENDS "roscpp" "rospy" "std_msgs")
set(tf_static_BUILDTOOL_DEPENDS "catkin")
set(tf_static_BUILDTOOL_EXPORT_DEPENDS )
set(tf_static_EXEC_DEPENDS "roscpp" "rospy" "std_msgs")
set(tf_static_RUN_DEPENDS "roscpp" "rospy" "std_msgs")
set(tf_static_TEST_DEPENDS )
set(tf_static_DOC_DEPENDS )
set(tf_static_URL_WEBSITE "")
set(tf_static_URL_BUGTRACKER "")
set(tf_static_URL_REPOSITORY "")
set(tf_static_DEPRECATED "")